/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2.my2dgame;

/**
 *
 * @author keyex
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemLabel = new javax.swing.JLabel();
        imagem2Label = new javax.swing.JLabel();
        image3Label = new javax.swing.JLabel();
        image4Label = new javax.swing.JLabel();
        image5Label = new javax.swing.JLabel();
        image6Label = new javax.swing.JLabel();
        image7Label = new javax.swing.JLabel();
        doctordown1 = new javax.swing.JLabel();
        doctordown2 = new javax.swing.JLabel();
        teste1 = new javax.swing.JLabel();
        monsterSlime1 = new javax.swing.JLabel();
        monsterSlime2 = new javax.swing.JLabel();
        attackUp1 = new javax.swing.JLabel();
        attackUp2 = new javax.swing.JLabel();
        attackDown1 = new javax.swing.JLabel();
        attackDown2 = new javax.swing.JLabel();
        attackLeft1 = new javax.swing.JLabel();
        attackLeft2 = new javax.swing.JLabel();
        attackRight1 = new javax.swing.JLabel();
        attackRight2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagemLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_down_1.png"))); // NOI18N

        imagem2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_down_2.png"))); // NOI18N

        image3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_left_1.png"))); // NOI18N

        image4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_left_2.png"))); // NOI18N

        image5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_right_1.png"))); // NOI18N

        image6Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_right_2.png"))); // NOI18N

        image7Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_up_1.png"))); // NOI18N

        doctordown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctordown1.png"))); // NOI18N

        doctordown2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctordown2.png"))); // NOI18N

        teste1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctordown1teste.png"))); // NOI18N

        monsterSlime1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenslime_down_1.png"))); // NOI18N

        monsterSlime2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenslime_down_2.png"))); // NOI18N

        attackUp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_up_1.png"))); // NOI18N

        attackUp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_up_2.png"))); // NOI18N

        attackDown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_down_1.png"))); // NOI18N

        attackDown2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_down_2.png"))); // NOI18N

        attackLeft1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_left_1.png"))); // NOI18N

        attackLeft2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_left_2.png"))); // NOI18N

        attackRight1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_right_1.png"))); // NOI18N

        attackRight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy_attack_right_2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(image3Label)
                        .addGap(127, 127, 127)
                        .addComponent(image5Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(monsterSlime1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monsterSlime2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(image4Label)
                                .addGap(152, 152, 152))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(image7Label)
                                    .addComponent(imagem2Label))
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctordown1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teste1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctordown2)
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(imagemLabel)
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(attackDown1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(image6Label)
                                                        .addGap(59, 59, 59))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(attackDown2)
                                                        .addContainerGap())))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(attackUp1)
                                                .addGap(18, 18, 18)
                                                .addComponent(attackUp2)
                                                .addGap(110, 110, 110)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(attackRight1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(attackRight2)
                                            .addContainerGap()))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(attackLeft1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(attackLeft2)
                                        .addGap(100, 100, 100))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(image4Label)
                .addGap(10, 10, 10)
                .addComponent(image7Label)
                .addGap(40, 40, 40)
                .addComponent(imagem2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monsterSlime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monsterSlime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attackUp1)
                    .addComponent(attackUp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image5Label)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(attackDown1)
                                .addGap(4, 4, 4))
                            .addComponent(attackDown2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attackLeft1)
                            .addComponent(attackLeft2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(imagemLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attackRight1)
                            .addComponent(attackRight2))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teste1)
                            .addComponent(doctordown1)
                            .addComponent(doctordown2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image6Label)
                        .addGap(4, 4, 4)
                        .addComponent(image3Label)
                        .addGap(57, 57, 57)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attackDown1;
    private javax.swing.JLabel attackDown2;
    private javax.swing.JLabel attackLeft1;
    private javax.swing.JLabel attackLeft2;
    private javax.swing.JLabel attackRight1;
    private javax.swing.JLabel attackRight2;
    private javax.swing.JLabel attackUp1;
    private javax.swing.JLabel attackUp2;
    private javax.swing.JLabel doctordown1;
    private javax.swing.JLabel doctordown2;
    private javax.swing.JLabel image3Label;
    private javax.swing.JLabel image4Label;
    private javax.swing.JLabel image5Label;
    private javax.swing.JLabel image6Label;
    private javax.swing.JLabel image7Label;
    private javax.swing.JLabel imagem2Label;
    private javax.swing.JLabel imagemLabel;
    private javax.swing.JLabel monsterSlime1;
    private javax.swing.JLabel monsterSlime2;
    private javax.swing.JLabel teste1;
    // End of variables declaration//GEN-END:variables
}
